### ISSUE TITLE
求博主文章链接

### ISSUE THREAD

**Issue by SilentAndSoft** [JustryDeng/PublicRepository#1]
博主您好，请问《程序员成长笔记(一)》和《程序员成长笔记(二)》的链接能粘一下吗？找了好久没找到

**Comment by JustryDeng** [comment]
朋友您好，这是我的学习笔记，暂未公布哦。 等以后知识沉淀下来后，我再整理整理，发出来。

**Comment by SilentAndSoft** [comment]
好的 感谢您的回复
